# Generated by Django 5.0.6 on 2024-06-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0002_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
