# Generated by Django 5.0.6 on 2024-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0003_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('messages', models.CharField(max_length=255)),
            ],
        ),
    ]
