# Generated by Django 5.0.6 on 2024-07-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0004_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_address', models.CharField(max_length=50)),
                ('remote_address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
